require "#{Rails.root}/db/gioco/create_badge_First Customer_Customer.rb"
require "#{Rails.root}/db/gioco/create_badge_Five Customers_Customer.rb"
require "#{Rails.root}/db/gioco/create_badge_Ten Customers_Customer.rb"
require "#{Rails.root}/db/gioco/create_badge_15 Customers_Customer.rb"
require "#{Rails.root}/db/gioco/create_badge_First Sale_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_Sales Intern_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_Sales Intern_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_Sales Manager_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_VP of Sales_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_CEO_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_Learjet_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_New Office_Order_Subtotal.rb"
require "#{Rails.root}/db/gioco/create_badge_Facebook Referral_Facebook.rb"
require "#{Rails.root}/db/gioco/create_badge_Twitter Referral_Twitter.rb"
require "#{Rails.root}/db/gioco/create_badge_Pinterest Referral_Pinterest.rb"
